version: "3.8"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  web:
    build: .
    command: uvicorn src.api.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/api/
    container_name: api_template_accidents
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus_template_accidents
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana_template_accidents
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      